2025-03-02 15:31:16,585 INFO    MainThread:58358 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-02 15:31:16,585 INFO    MainThread:58358 [wandb_setup.py:_flush():67] Configure stats pid to 58358
2025-03-02 15:31:16,585 INFO    MainThread:58358 [wandb_setup.py:_flush():67] Loading settings from /Users/tawneykirkland/.config/wandb/settings
2025-03-02 15:31:16,585 INFO    MainThread:58358 [wandb_setup.py:_flush():67] Loading settings from /Users/tawneykirkland/credit/modeling/wandb/settings
2025-03-02 15:31:16,585 INFO    MainThread:58358 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-02 15:31:16,585 INFO    MainThread:58358 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /Users/tawneykirkland/credit/modeling/wandb/run-20250302_153116-m7wt9oxy/logs/debug.log
2025-03-02 15:31:16,585 INFO    MainThread:58358 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /Users/tawneykirkland/credit/modeling/wandb/run-20250302_153116-m7wt9oxy/logs/debug-internal.log
2025-03-02 15:31:16,585 INFO    MainThread:58358 [wandb_init.py:init():761] calling init triggers
2025-03-02 15:31:16,585 INFO    MainThread:58358 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'n_estimators': 100, 'max_depth': 10, 'test_size': 0.25, 'random_state': 12, '_wandb': {}}
2025-03-02 15:31:16,585 INFO    MainThread:58358 [wandb_init.py:init():784] starting backend
2025-03-02 15:31:16,585 INFO    MainThread:58358 [wandb_init.py:init():788] sending inform_init request
2025-03-02 15:31:16,624 INFO    MainThread:58358 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-03-02 15:31:16,625 INFO    MainThread:58358 [wandb_init.py:init():803] backend started and connected
2025-03-02 15:31:16,627 INFO    MainThread:58358 [wandb_init.py:init():896] updated telemetry
2025-03-02 15:31:16,644 INFO    MainThread:58358 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-02 15:31:16,881 INFO    MainThread:58358 [wandb_init.py:init():995] starting run threads in backend
2025-03-02 15:31:16,958 INFO    MainThread:58358 [wandb_run.py:_console_start():2377] atexit reg
2025-03-02 15:31:16,958 INFO    MainThread:58358 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-02 15:31:16,958 INFO    MainThread:58358 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-02 15:31:16,959 INFO    MainThread:58358 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-02 15:31:16,963 INFO    MainThread:58358 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-02 15:32:00,877 INFO    MainThread:58358 [wandb_run.py:_config_callback():1261] config_cb ('_wandb', 'viz', 'confusion_matrix') {'id': 'wandb/confusion_matrix/v1', 'historyFieldSettings': {'x-axis': '_step', 'key': 'confusion_matrix'}} None
2025-03-02 15:32:01,143 WARNING MsgRouterThr:58358 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/Users/tawneykirkland/credit/venv/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tawneykirkland/credit/venv/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tawneykirkland/credit/venv/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/tawneykirkland/credit/venv/lib/python3.11/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/Users/tawneykirkland/credit/venv/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-02 15:32:01,144 INFO    MsgRouterThr:58358 [mailbox.py:close():115] Closing mailbox, abandoning 2 handles.
